SITUATION: 1 amendment OK, other fails. When retry amendment triggered, we get this error

chain:blockgenerator (task_queues:96:5,chain.js:1037:20,scheduleAction.js:51:5) SCHEDULE [4] 34284ms {
    from: 'chain:alice',
    type: 'amendment_timeout',
    data: { id: 114 },
    id: 3,
    executeBlock: 11
  } +0ms
    chain:alice (task_queues:96:5,chain.js:1039:9) INFO [47] 34285ms { text: 'new event emitted', type: 'NewAmendment', task_id: 114 } +0ms
    chain (task_queues:96:5,chain.js:78:7) CURRENT-BLOCK [510] 34285ms 6 +0ms
  /home/ninabreznik/Documents/code/play/datdot/service/node_modules/brotli/build/encode.js:3
  1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");b.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",function(a){if(!(a instanceof y))throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(x)b.print||(b.print=print),"undefined"!=typeof printErr&&(b.printErr=printErr),b.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},b.readBinary=function(a){if("function"===
                                                                                                                                                                                                                                ^
  
  Error: ETIMEDOUT
      at ProtocolStream.<anonymous> (/home/ninabreznik/Documents/code/play/datdot/service/node_modules/hypercore-protocol/index.js:363:51)
      at Object.onceWrapper (node:events:471:28)
      at ProtocolStream.emit (node:events:365:28)
      at Timeout.call (/home/ninabreznik/Documents/code/play/datdot/service/node_modules/timeout-refresh/refresh.js:25:18)
      at listOnTimeout (node:internal/timers:559:11)
      at processTimers (node:internal/timers:500:7)
  Emitted 'error' event on ProtocolStream instance at:
      at WritableState.afterDestroy (/home/ninabreznik/Documents/code/play/datdot/service/node_modules/streamx/index.js:442:19)
      at ProtocolStream._destroy (/home/ninabreznik/Documents/code/play/datdot/service/node_modules/hypercore-protocol/index.js:439:5)
      at WritableState.updateNonPrimary (/home/ninabreznik/Documents/code/play/datdot/service/node_modules/streamx/index.js:189:16)
      at WritableState.update (/home/ninabreznik/Documents/code/play/datdot/service/node_modules/streamx/index.js:174:70)
      at WritableState.updateWriteNT (/home/ninabreznik/Documents/code/play/datdot/service/node_modules/streamx/index.js:482:8)
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
    chain (chain.js:125:7)=>[ERROR] unexpected closing of chain connection for INFO [0] 34763ms [ 'chain' ] +0ms
    rachel (timers:557:17,user.js:64:5) KEEP-ALIVE [16] 34992ms [ '. . .' ] +0ms
    eve (timers:557:17,user.js:64:5) KEEP-ALIVE [16] 35188ms [ '. . .' ] +0ms